[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/exclusive/vip-cost-8848"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/exclusive/vip-supply-9961"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/exclusive/huawei-cost.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/exclusive/huawei-stocks.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
